CREATE TABLE Customer (ID int(10) NOT NULL AUTO_INCREMENT, FirstName varchar(255), PRIMARY KEY (ID)) CHARACTER SET UTF8;
CREATE TABLE Vehicle (ID int(10) NOT NULL AUTO_INCREMENT, CustomerID int(10) NOT NULL, Name varchar(255), Type varchar(255), PRIMARY KEY (ID)) CHARACTER SET UTF8;
ALTER TABLE Vehicle ADD INDEX FKVehicle144311 (CustomerID), ADD CONSTRAINT FKVehicle144311 FOREIGN KEY (CustomerID) REFERENCES Customer (ID);
